module.exports = {
  INTERNAL_SERVER_ERROR: 'Oops, something broke on the server!!!',
  NOT_FOUND_API: 'Oops, You have reached a dead end',
  INVALID_PERMISSION: 'Permission denied. Current user does not have the required permission to access this resource.',
  INVALID_CREDENTIALS: 'Incorrect login details',
  ACCESS_REVOKED: 'Your access has been revoked',
  AUTH_REQUIRED: 'Access denied,a valid access token is required',
  UNAUTHORIZED: 'Unauthorised Access to this resource',
  DB_ERROR_STATUS: 'DB_PROCESS_FAILED',
  MODULE_ERROR_STATUS: 'MODULE_PROCESS_BROKE',
  SUCCESS: 'success',
  SUCCESS_RESPONSE: 'Request was successfully processed',
  FAIL: 'fail',
  WELCOME: 'Thanks for dropping by, you are at Farmvesty',
  v1: '/api/v1',
  GENERIC_ERROR: 'Sorry, something went wrong',
  DB_ERROR: 'A database error occurred,',
  MODULE_ERROR: 'A module error occurred',
}
